#!/usr/bin/env bash

website_path="$1";
if [[ $website_path = "" ]]; then
  echo "✘ You must pass a path to a norska website as the first argument"
  exit 1
fi

# Restart the server whenever backend code changes
nodemon \
  --exec "cd $website_path && yarn run norska cms" \
  --watch "./build" 
