# Build website
[build]
  command = "yarn run build:prod"
  publish = "./modules/docs/dist/"

# Terry Pratchett homage
[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
