version: 2.1

aliases:
  - &defaults
    docker:
      - image: cimg/node:14.17.0
  - &restore_cache
    restore_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
  - &yarn_install
    run: 'yarn install'
  - &save_cache
    save_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

jobs:
  # Test / Lint
  ci:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      - *save_cache
      - run: 'yarn run ci'

workflows:
  version: 2
  # On every commit: Test / Lint
  commit:
    jobs:
      - ci
