version: 2.1

aliases:
  - &defaults
    docker:
      - image: circleci/node:12.12.0
  - &restore_cache
    restore_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
  - &yarn_install
    run: 'yarn install'
  - &save_cache
    save_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

jobs:
  # Build/Test/lint
  ci:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      - *save_cache
      - run: 'yarn run ci'

workflows:
  version: 2
  # On every commit: Build/Test/Lint
  commit:
    jobs:
      - ci
